CREATE TABLE IF NOT EXISTS players (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  steam_id TEXT UNIQUE NOT NULL,
  name TEXT NOT NULL,
  avatar TEXT,
  kd FLOAT DEFAULT 0,
  win_rate FLOAT DEFAULT 0,
  total_hours INTEGER DEFAULT 0,
  hs_percentage FLOAT DEFAULT 0,
  level INTEGER DEFAULT 0,
  aim_score INTEGER DEFAULT 0,
  utility_score INTEGER DEFAULT 0,
  positioning_score INTEGER DEFAULT 0,
  opening_score INTEGER DEFAULT 0,
  clutch_score INTEGER DEFAULT 0,
  leetify_rating FLOAT DEFAULT 0,
   faceit_elo INTEGER DEFAULT 0,
  auth_code TEXT,
  auth_code_valid BOOLEAN DEFAULT TRUE,
  latest_match_id TEXT,
  wins INTEGER DEFAULT 0,
  losses INTEGER DEFAULT 0,
  ties INTEGER DEFAULT 0,
  total_matches INTEGER DEFAULT 0,
  waiting_matches INTEGER DEFAULT 0,
  avg_kd FLOAT DEFAULT 0,
  avg_adr FLOAT DEFAULT 0,
  avg_hs FLOAT DEFAULT 0,
  avg_kast FLOAT DEFAULT 0,
  avg_accuracy FLOAT DEFAULT 0,
  avg_ttd FLOAT DEFAULT 0,
  avg_rating FLOAT DEFAULT 0,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. Create the Reviews table with explicit constraint names
CREATE TABLE IF NOT EXISTS reviews (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  author_id TEXT,
  target_id TEXT,
  rating TEXT NOT NULL,
  comment TEXT,
  badges TEXT, 
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  CONSTRAINT reviews_author_id_fkey FOREIGN KEY (author_id) REFERENCES players(steam_id),
  CONSTRAINT reviews_target_id_fkey FOREIGN KEY (target_id) REFERENCES players(steam_id)
);

-- 3. Create the ReputationScore table
CREATE TABLE IF NOT EXISTS reputation_scores (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  user_id TEXT UNIQUE,
  score FLOAT DEFAULT 0,
  total_votes INTEGER DEFAULT 0,
  positive_votes INTEGER DEFAULT 0,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  CONSTRAINT reputation_scores_user_id_fkey FOREIGN KEY (user_id) REFERENCES players(steam_id)
);

-- 4. Create the Leaderboard Entries table for real-time syncing
CREATE TABLE IF NOT EXISTS leaderboard_entries (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  region TEXT NOT NULL,
  rank INTEGER NOT NULL,
  cs_rating INTEGER NOT NULL,
  name TEXT NOT NULL,
  time_achieved TIMESTAMP WITH TIME ZONE,
  last_seen TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  CONSTRAINT leaderboard_entries_region_rank_key UNIQUE (region, rank)
);

-- Note: In the Supabase SQL Editor, you might need to enable RLS Policies:
-- 1. Go to Authentication -> Policies
-- 2. Add 'public' select/insert/update/delete access for all tables for testing.
